# Generated by Django 5.1.1 on 2024-10-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='connect_url',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
